### ISSUE TITLE
test repos should not combine debian versions

### ISSUE THREAD

**Issue by andrewschoen** [ceph/chacra#196]
For our chacra gitbuilder nodes we do not want to combine debian versions into one repo. We need to remove this configuration from all test chacra nodes: https://github.com/ceph/chacra/blob/master/deploy/playbooks/roles/common/templates/prod.py.j2#L116

In the example we found it also mixed two different sha1s into the same repo: https://2.chacra.ceph.com/r/ceph/master/b8c203fb64c80fe52a4d17562ddef39371347d42/ubuntu/xenial/flavors/default/pool/main/c/ceph/

**Comment by dmick** [comment]
why don't we want combined repos?

**Comment by alfredodeza** [comment]
@dmick the repositories for ceph-dev builds (a.k.a. new gitbuilders) are meant to be unique, containing only binaries built for the given sha1.

The "combined" behavior is something we have ON by default because the initial use case was upstream releases which have multiple different distro binaries in them. 

The use case for these repos means that we will never want that behavior because combining them will cause situations where multiple different sha1's are included in the same repo (defeating the purpose of uniqueness).

It also means more work to build/re-build repositories.

**Comment by alfredodeza** [comment]
This was opened after the discussion in: https://github.com/ceph/shaman/issues/57

**Comment by andrewschoen** [comment]
@alfredodeza actually, we might have another bug here. Even if we did want to combine debian versions into the same repo, I don't think we'd want them across different sha1s.

Should we be filtering by sha1 here as well as ref? https://github.com/ceph/chacra/blob/master/chacra/async/debian.py#L94

**Comment by dmick** [comment]
Multiple distroversions does not imply multiple sha1s; neither does multiple arch (for example).

I wonder if we want to carefully consider the one repo == one sha1/distro/distroversion/arch choice.  It'll clearly work, but it's unnecessary.
